export const usuarios = [
    {
		Fecha_de_habilitación:"44742",
		Oblea_anterior:"43410099",
		Fecha_de_vencimiento:"45107",
		Fecha_Oblea_anterior:"44742",
		Codigo_PEC:"3455",
		Codigo_de_taller:"HIT0749",
		Vehículo_Marca:"RENAULT",
		Modelo:"Duster Oroch",
		Año:"2018",
		Tipo_de_Operación:"REVISION ANUAL",
		Dominio:"AD129AM",
		Inyección:"NO",
		Tipo_de_Vehículo:"PARTICULAR",
		Propietario_Nombre_y_Apellido:"PAIVA DAVID",
		Dirección:"LOS PLATANOS 1517",
		Codigo_Postal:"5010",
		Localidad:"CORDOBA",
		Teléfono:"351 2893007",
		Tipo_y_Nro_Documento:"DNI 25.918.879",
		Codigo_Actual:"TY02",
		Codigo_Montaje:"",
		Codigo_Desmontaje:"",
		Codigo_Baja:"",
		Nro_Serie_Actual:"PPA1097269",
		Nro_Serie_Montaje:"",
		Nro_Serie_Desmontaje:"",
		Nro_Serie_Baja:"",
		Codigo:"KJ38",
		Nro_Serie:"627127",
		Nuevo:"",
		Usado:"x",
		Fabricado_Mes:"2",
		Fabricado_Año:"18",
		Revisado_Mes: "02",
		Revisado_Ano: "23",
		CRPC: "SORV",
		OP: "S",
		Codigo_Valvula: "TY87",
		Nro_Serie_Valvula: "DFA1066853",
		OP_V: "S"   
    },
    {
		Fecha_de_habilitación:"45112",
		Oblea_anterior:"42410156",
		Fecha_de_vencimiento:"45112",
		Fecha_Oblea_anterior:"45112",
		Codigo_PEC:"3456",
		Codigo_de_taller:"HIT0749",
		Vehículo_Marca:"FORD",
		Modelo:"Fiesta Kinectic",
		Año:"2019",
		Tipo_de_Operación:"REVISION ANUAL",
		Dominio:"AD363JC",
		Inyección:"NO",
		Tipo_de_Vehículo:"PARTICULAR",
		Propietario_Nombre_y_Apellido:"CORINTO JORGE",
		Dirección:"MAESTRO VIDAL 1574",
		Codigo_Postal:"5010",
		Localidad:"CORDOBA",
		Teléfono:"351 2522363",
		Tipo_y_Nro_Documento:"DNI 23.998.654",
		Codigo_Actual:"TY01",
		Codigo_Montaje:"",
		Codigo_Desmontaje:"",
		Codigo_Baja:"",
		Nro_Serie_Actual:"PPA1026654",
		Nro_Serie_Montaje:"",
		Nro_Serie_Desmontaje:"",
		Nro_Serie_Baja:"",
		Codigo:"KS29",
		Nro_Serie:"652365",
		Nuevo:"",
		Usado:"x",
		Fabricado_Mes:"5",
		Fabricado_Año:"19",
		Revisado_Mes: "05",
		Revisado_Ano: "19",
		CRPC: "SORV",
		OP: "S",
		Codigo_Valvula: "TY88",
		Nro_Serie_Valvula: "DFA10765523",
		OP_V: "S"   		
    },
    {
		Fecha_de_habilitación:"45112",
		Oblea_anterior:"42410156",
		Fecha_de_vencimiento:"45112",
		Fecha_Oblea_anterior:"45112",
		Codigo_PEC:"3456",
		Codigo_de_taller:"HIT0749",
		Vehículo_Marca:"FORD",
		Modelo:"Fiesta_Kinectic",
		Año:"2019",
		Tipo_de_Operación:"MODIFICACION",
		Dominio:"AB546JS",
		Inyección:"NO",
		Tipo_de_Vehículo:"PARTICULAR",
		Propietario_Nombre_y_Apellido:"RODRIGUEZ JORGE",
		Dirección:"SAN LUIS 825",
		Codigo_Postal:"5000",
		Localidad:"CORDOBA",
		Teléfono:"351 2653962",
		Tipo_y_Nro_Documento:"DNI 27652312",
		Codigo_Actual:"TY02",
		Codigo_Montaje:"",
		Codigo_Desmontaje:"",
		Codigo_Baja:"",
		Nro_Serie_Actual:"PPF1023536",
		Nro_Serie_Montaje:"",
		Nro_Serie_Desmontaje:"",
		Nro_Serie_Baja:"",
		Codigo:"KX13",
		Nro_Serie:"685236",
		Nuevo:"",
		Usado:"x",
		Fabricado_Mes:"4",
		Fabricado_Año:"11",
		Revisado_Mes: "07",
		Revisado_Ano: "21",
		CRPC: "NOVA",
		OP: "S",
		Codigo_Valvula: "TY84",
		Nro_Serie_Valvula: "DFA10163326",
		OP_V: "S"   		
		
    },
    {
		Fecha_de_habilitación:"44813",
		Oblea_anterior:"42563253",
		Fecha_de_vencimiento:"45178",
		Fecha_Oblea_anterior:"44813",
		Codigo_PEC:"3536",
		Codigo_de_taller:"HIT0749",
		Vehículo_Marca:"RENAULT",
		Modelo:"Sandero",
		Año:"2015",
		Tipo_de_Operación:"RENOVACION ANUAL",
		Dominio:"NRM783",
		Inyección:"NO",
		Tipo_de_Vehículo:"PARTICULAR",
		Propietario_Nombre_y_Apellido:"CACHAVIGLIANI JOSE LUIS",
		Dirección:"TEMISTOCLES CASTELLANOS 2315",
		Codigo_Postal:"5016",
		Localidad:"CORDOBA",
		Teléfono:"3543256458",
		Tipo_y_Nro_Documento:"DNI_21554652",
		Codigo_Actual:"TY01",
		Codigo_Montaje:"",
		Codigo_Desmontaje:"",
		Codigo_Baja:"",
		Nro_Serie_Actual:"PPO09256325",
		Nro_Serie_Montaje:"",
		Nro_Serie_Desmontaje:"",
		Nro_Serie_Baja:"",
		Codigo:"KX14",
		Nro_Serie:"5623145",
		Nuevo:"",
		Usado:"x",
		Fabricado_Mes:"4",
		Fabricado_Año:"11",
		Revisado_Mes: "01",
		Revisado_Ano: "22",
		CRPC: "SORV",
		OP: "S",
		Codigo_Valvula: "TY87",
		Nro_Serie_Valvula: "DFA10564427",
		OP_V: "S"   		
		
    }
    
]
    